import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokédex by Yang Liu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Pokédex
        </h1>
        <Image src="/pokeball.png" alt="Pokeball" width={120} height={120} />
      </main>

      <footer className={styles.footer}>
        <p>Developed by Yang Liu &#169; 2021</p>
      </footer>
    </div>
  )
}

export default Home
