import React, { useEffect, useState, FC } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  interface Props {
    src: string;
    width: number;
    quality: number;
  }

  const [pokemonData, setPokemonData] = useState([]);

  useEffect(() => {
    getData();
  }, []);

  const getData = async () => {
    const res = await fetch("https://pokeapi.co/api/v2/pokemon/?limit=20");
    const data = await res.json();
    // console.log("data", data);
    // console.log("data results", data.results);
    setPokemonData(data.results);
  };

  const PokemonDataMapped = pokemonData.map((item: any, index: number) => (
    // <div key={index}>
    <a
      key={index}
      href={`https://bulbapedia.bulbagarden.net/wiki/${item.name}_(Pok%C3%A9mon)`}
      className={styles.card}
    >
      <Image
        alt="pokemon"
        src={`https://github.com/PokeAPI/sprites/blob/master/sprites/pokemon/other/official-artwork/${
          index + 1
        }.png?raw=true`}
        width={200}
        height={200}
        layout="fixed"
      />
      <p>{item.name}</p>
    </a>
    // </div>
  ));

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokédex by Yang Liu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.flexRow}>
          <h1 className={styles.title}>Pokédex</h1>
          <Image
            src="/pokeball.png"
            alt="Pokeball"
            width={120}
            height={120}
            layout="fixed"
          />
        </div>
        <div className={styles.grid}>{PokemonDataMapped}</div>
      </main>

      <footer className={styles.footer}>
        <p>Developed by Yang Liu &#169; 2021</p>
      </footer>
    </div>
  );
};

export default Home;
